drop function create_empty_coach();
drop function remove_group_person();
drop function remove_list_person();
drop function get_money_from_account();
drop function check_person_eat_calendar();
drop function create_group_chat();
drop function check_coach_birthday();
drop function check_update_eat_calendar();
drop function check_update_training_date();
drop function check_group_count_for_training();
drop function coach_filtration(varchar, integer, integer, integer, integer);
drop function get_person_trainings(integer);
drop function get_person_eat_calendar(integer);
drop function get_all_person_in_group(integer);
drop function get_all_person_in_group_chat(integer);
drop function get_all_messages_in_group_chat(integer);